defmodule Badge.Rickroll do
  @moduledoc """
  Frames of a certain music video, for the Sudo Mode page.

  Stored at 48x48 and drawn at 3x, the same trick the shape icons use: a
  ninth of the bytes for the same 144x144 on screen. Generated by
  `tools/gif.py`, which samples evenly across the source animation.

  Literals are packed uncompressed by ExAtomVM and read straight from
  mapped flash, so these frames cost flash rather than heap.
  """

  @compile {:no_warn_undefined, :atomvm}

  @dir Path.expand("../../assets/rickroll", __DIR__)

  # The directory itself, so adding or removing frames recompiles this module.
  @external_resource @dir

  @files Enum.sort(Path.wildcard(Path.join(@dir, "*.rgba")))

  for file <- @files do
    @external_resource file
  end

  @size (case @files do
           [] ->
             0

           [first | _rest] ->
             first
             |> Path.basename(".rgba")
             |> String.split("@")
             |> List.last()
             |> String.split("x")
             |> hd()
             |> String.to_integer()
         end)

  @scale 3

  # The bytes are not kept, but a frame of the wrong size still fails the build.
  for file <- @files do
    data = File.read!(file)

    byte_size(data) == @size * @size * 4 ||
      raise "#{Path.basename(file)}: #{byte_size(data)} bytes, expected #{@size * @size * 4}"
  end

  @count length(@files)

  @count > 0 || raise "no frames in #{@dir}; run tools/gif.py"

  @doc "How many frames the loop has."
  def count, do: @count

  @doc "Size of a frame once drawn."
  def size, do: @size * @scale

  @doc "A display item for one frame, wrapping round if the index runs past either end."
  @spec item(integer, integer, integer) :: tuple
  def item(index, x, y) do
    {:scaled_cropped_image, x, y, @size * @scale, @size * @scale, 0x000000, 0, 0, @scale, @scale,
     [], {:rgba8888, @size, @size, frame(wrap(index))}}
  end

  # A clock that started below zero, as the host's does, still lands on a frame.
  defp wrap(index), do: rem(rem(index, @count) + @count, @count)

  # Names are fixed at compile time; the bytes come from the assets partition.
  for {file, index} <- Enum.with_index(@files) do
    name = ~c"rickroll/" ++ String.to_charlist(Path.basename(file))
    defp frame(unquote(index)), do: :atomvm.read_priv(:assets, unquote(name))
  end
end
